// <auto-generated />
using System;
using CoronaSymptoms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoronaSymptoms.Migrations
{
    [DbContext(typeof(SymptomerContext))]
    [Migration("20200317135731_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoronaSymptoms.Models.Symptomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Andet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Diarre")
                        .HasColumnType("bit");

                    b.Property<bool>("Feber")
                        .HasColumnType("bit");

                    b.Property<bool>("Halsonde")
                        .HasColumnType("bit");

                    b.Property<bool>("Hoster")
                        .HasColumnType("bit");

                    b.Property<bool>("Hovedpine")
                        .HasColumnType("bit");

                    b.Property<string>("Køn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Muskelømhed")
                        .HasColumnType("bit");

                    b.Property<bool>("Nyser")
                        .HasColumnType("bit");

                    b.Property<bool>("Opkast")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sansetab")
                        .HasColumnType("bit");

                    b.Property<bool>("Stakåndethed")
                        .HasColumnType("bit");

                    b.Property<bool>("SymptomerBool")
                        .HasColumnType("bit");

                    b.Property<bool>("Udmattet")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Symptomer");
                });
#pragma warning restore 612, 618
        }
    }
}
